# Generated by Django 5.1.5 on 2025-05-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('beverages', 'Beverages'), ('desserts', 'Desserts')], max_length=50)),
                ('image', models.ImageField(upload_to='menu/')),
            ],
        ),
    ]
