# Generated by Django 5.1.5 on 2025-05-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default='No description available.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(default='No description available.'),
            preserve_default=False,
        ),
    ]
