# Generated by Django 5.1.5 on 2025-05-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_remove_menuitem_category_remove_menuitem_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image_url',
        ),
    ]
