# Generated by Django 5.1.5 on 2025-05-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_remove_menuitem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='No description available.', upload_to=''),
            preserve_default=False,
        ),
    ]
